### ISSUE TITLE
First pass over pretzel plot

### ISSUE THREAD

**Issue by rolyp** [WarwickCIM/backfillz-py#2]
`plot_trace_dial()` and related functionality. See [here](https://github.com/WarwickCIM/backfillz) for the R version.

Done/dropped:
- [x] histograms should not be grouped
- [x] white angular “zero line” (half way up radial axis – not actually zero)
- [x] histograms should omit summary of all chains
- [x] histo plot per chain, not KDE curve
- [x] burn-in segment experiments 
  - [x] pie plot (for segment shading) with scatterpolar (with transparent background)<br>:x: without z-order doesn’t seem to be a way to force pie plot to be under scatterpolar
  - [x] decompose scatterpolar into two contiguous scatterpolar plots
    - [x] set x domain explicitly to force polar plots to overlay<br>:x: subplots are scaled to fit the same region and no way to link scaling
  - [x] render donus explicitly using`add_shape`
    - [x] `scaleanchor` to stop circles being stretched<br>:x: not easy to draw circle segment 
- [x] plot chains around 3/4 circle
  - [x] `Scatterpolar` experiment
  - [x] drop labels from angular axis 
  - [x] horizontal orientation for radial axis tick labels
- [x] vertical title on each histogram
- [x] background 3/4 donut
  - [x] `go.Pie` experiment
    - [x] specify order of segments (`sort=False`)
  - [x] segment according to slices
  - [x] lose % labels
- [x] new test case and skeleton of plot
  - [x] extract `RootPlot` class 
  - [x] `TraceDial` class with `DialPlot` and `Histograms` subplots
  - [x] extract common test configuration to setup/tear down methods
  - [x] `Specs` layout
- [x] histograms in upper-right quadrant (one per slice)
  - [x] split more abstract base class out of `LeafPlot` that doesn’t provide `layout_axes`
  - [x] initial import of histogram plots from trace slice histogram 
  - [x] set `domain` on `go.Pie` plot
  - [x] lose title from histogram plots
  - [x] omit bottom x-axis from histograms (mostly hidden by torus anyway)
  - [x] Plotly doesn’t support trace z-order 😩  
    - [x] work around by rendering upper quadrant with zero opacity
  - [x] length of histogram x-axis to be width of torus
    - [x] manually adjust domain of x-axis – fragile but reduces problem to one of finding appropriate ratio  
- [x] some consolidation/generalisation of `ChartData`, etc
  - [x] move `Slice` to `core`?
  - [x] `ChartData` -> `ParameterSlices` (and omit `theme`)?
  - [x] `Subplot` -> `LeafPlot`?
- [x] header and footer titles
- [x] switch from Plotly polar coordinates to Cartesian reference frame
  - [x] new implementation of `polar_traces` based on `go.Scatter` rather than `go.Scatterpolar` 
    - [x] check we can use `go.Scatter` to draw closed shape
    - [x] use `go.Scatter` to approximate (3/4) circle
    - [x] link x-axis and y-axis scales
  - [x] Plotly `shapes` experiment with SVG `path` property
    - [x] use `A` path element to specify arc :x: Plotly doesn’t support SVG arc paths 🤦 
  - [x] draw donut as closed scatterplot 
  - [x] fill
  - [x] setting `range` on axes to `[-1, 1]` isn’t fixing range of axes
  - [x] drop x and y axes
  - [x] reinstate 2nd histogram 
  - [x] reinstate histogram titles
- [x] length of histogram x-axis to be width of torus
  - <s>experiment with [setting plot size/aspect ratio](https://github.com/plotly/plotly.py/issues/70)</s> – shouldn’t be required if we plot manually
  - [x] set figure to be square :x: plotting region is still some rectangular region inside the square  
  - [x] keep as (roughly) square but disable `scaleanchor='y', scaleratio=1`)
  - [x] eliminate `x_to_y` magic ratio
- [x] fix order of burn-in histogram and rest of sample
- [x] check in Safari/Firefox
- [x] segment of 3/4 donut for each slice
  - [x] push `normalise` behaviour for xs inside `polar_plot` 
  - [x] push `to_radial` and `normalise` behaviour for ys inside `polar_plot`
  - [x] parameterise `polar_plot` on domain (in radians)
- [x] step plot to colour only upper edge of histograms
  - [x] aggregate of chains as histogram (?)
  - [x] each chain as individual step plot
    - [x] use `np.histogram` for binning, render with `go.Scatter` and line shape `hvh`
    - [x] one per chain, colour from palette
    - [x] resolve z-order question again -- might involve dropping `go.Histogram` in `SliceHistogram` 
    - [x] normalise histogram/step plot y-axes
- [x] histograms need to share x-axis
- [x] different colour settings for burn-in histogram
  - [x] transparent background for root plot 
  - [x] background colour for plot
- [x] angular axis with tick marks on inside of polar plot
  - [x] undo push of `normalise` behaviour inside `polar_plot` -- needs to plot against a fixed reference frame
  - [x] `Axis` abstraction for reifying reference frames
  - [x] `arc` helper, use to simplify `donut_segments`
  - <s>plot ticks using `arc`</s>
  - [x] plot ticks using `angular_axis` for correct placement w.r.t. range
  - [x] use `nan` to segment `go.Scatter`
  - [x] determine tick lengths
  - [x] longer ticks for start, end and burn-in end
  - [x] determine number of ticks
    - [x] ticks need to be relative to range of (angular) x-axis 
    - [x] heuristic for calculating number of ticks
    - [x] simplify
  - [x] text labels

**Comment by rolyp** [comment]
@GregMci @jamestripp (Hoping I can reach Greg with a GitHub mention!) Quick question: is there a reason the pretzel plot goes anti-clockwise? Clockwise seems more conventional, especially if the axis represents time or some quantity that increase with time (e.g. number of iterations).

To put it another way: as I come to understand what I’m looking at in the pretzel plot, I find that I mentally interpret myself as looking at the “back” of something. (If that makes sense.)

**Comment by rolyp** [comment]
@GregMci @jamestripp Hi again. I’ve noticed there are some differences between the plot generated by the R code:
![image](https://user-images.githubusercontent.com/121074/120470853-f1435100-c39b-11eb-8416-41fa74c230a2.png)
and the one at https://github.com/WarwickCIM/backfillz:
![image](https://user-images.githubusercontent.com/121074/120471156-454e3580-c39c-11eb-8dab-f9e770732c80.png)
Leaving colours aside, the main points to note about the R version are:
- image looks squashed along y-axis
- there are (vertical) titles on the histograms
- bars in histograms aren’t visible
- trace plot looks like it’s plotting a single chain (or aggregate of all chains)
- similar remark about histograms
- title says “spiral plot” (rather than “pretzel plot” or “trace dial”)

Initially I thought the shading/alpha transparency to distinguish the burn-in slice was missing, but actually that may be because the burn-in slice here is of length zero.

In terms of look-and-feel, I’m going to assume we want something more like the second image, but if we could discuss this when we next speak, that would be good. (Feel free to comment on any of the above in the meantime!)

**Comment by jamestripp** [comment]
Hi @rolyp ,

Thanks for getting in touch. Which IDE are you using (as that may effect your plot device) and what code did you run to get that output?

I've just grabbed the current version of Backfillz from GitHub and created the plot via backfillz::plot_trace_dial(backfillz:sample_stanfit) and get the below plot:
<img width="1778" alt="Screenshot 2021-06-02 at 13 34 11" src="https://user-images.githubusercontent.com/5781056/120480793-5486b080-c3a7-11eb-98f8-5491e020c09f.png">

The different colours in the trace and the histograms suggest it is plotting all the chains. The vertical titles were a late addition and good spot re the Spiral Plot title, that should be changed.

@GregMci, what are your thoughts re the differences between the two images?

**Comment by rolyp** [comment]
Thanks @jamestripp, that’s useful.

I’m using PyCharm on the Mac. The grey background and histogram bars that I’m not seeing could be a weird rendering issue/non-portable behaviour or perhaps something to with the translation to Postscript. We can probably put that issue to one side for now - obviously it would be nice to have the R version render consistently but it may be somewhat out of our control and it needn’t stop us making progress on the Python version.

The histogram plot is probably more significantly different, looking forward to @GregMci’s thoughts on this.
