### ISSUE TITLE
Sample Stan data

### ISSUE THREAD

**Issue by rolyp** [WarwickCIM/backfillz-py#6]
Need some sample Stan data to test the plotting functions. In the R version, this is loaded from `sample_stanfit.rda` (an R binary format). This seems to have been generated from the Eight Schools example in R; we can probably do something similar using PyStan.
- [x] `poetry add pystan`
- [x] generate the Eight Schools fit using the [sample Python code](https://pystan.readthedocs.io/en/latest/getting_started.html)
- [x] skeleton of `Backfillz` class and `as_backfillz` method
- [x] `poetry run flake8 backfillz/ tests/` locally
- [x] `poetry run mypy --strict --config-file=mypy.ini backfillz/` locally
- [x] `BackfillzTheme` class and prebuilt instances
- [x] bump to Python 3.8, install Pandas
- [x] `test_asBackfillz`:
  - [x] save/pickle baseline sample data as `expected_backfillz`
  - [x] load/unpickle `expected_backfillz` and compare

**Comment by jamestripp** [comment]
In R we use the hierarchical schools model from the [pystan documentation](https://pystan.readthedocs.io/en/latest/). I have also added documentation for the sample_stanfit objects on the backfillz page [https://warwickcim.github.io/backfillz/reference/sample_stanfit.html](here).

**Comment by rolyp** [comment]
Initial pass
